---
# tasks file for vector-role
---
- name: Get Vector distrib (Ubuntu/Debian)
  ansible.builtin.get_url:
    url: "{{ vector_download_url_deb }}"
    dest: "/tmp/vector-{{ vector_version }}.deb"
  when: ansible_os_family == "Debian"

- name: Install Vector (Ubuntu/Debian)
  ansible.builtin.apt:
    deb: "/tmp/vector-{{ vector_version }}.deb"
    state: present
  when: ansible_os_family == "Debian"
  notify: restart vector

- name: Create Vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Copy Vector config
  ansible.builtin.template:
    src: vector.toml.j2
    dest: "{{ vector_config_dir }}/vector.toml"
  notify: restart vector